// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class EditSchemaProduct_VariantTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditSchemaProduct_VariantTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202507110951282_EditSchemaProduct_VariantTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
